name: yafct
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.6.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
    
  common_core:
    path: packages/common_core

  common_logger:
    path: packages/common_logger

  presentation_core_styling:
    path: packages/presentation_core_styling

  presentation_core_ui:
    path: packages/presentation_core_ui

  data_network:
    path: packages/data_network

  data_database:
    path: packages/data_database

  data_preference:
    path: packages/data_preference

  data_repository:
    path: packages/data_repository

  domain_repository:
    path: packages/domain_repository

  presentation_feature_main:
    path: packages/presentation_feature_main

  presentation_feature_detalization:
    path: packages/presentation_feature_detalization

  presentation_feature_splash:
    path: packages/presentation_feature_splash

  presentation_feature_user_details:
    path: packages/presentation_feature_user_details

  presentation_feature_user_profile:
    path: packages/presentation_feature_user_profile

  presentation_feature_welcome:
    path: packages/presentation_feature_welcome

  presentation_feature_account_settings:
    path: packages/presentation_feature_account_settings

  go_router: ^15.0.0
  flutter_bloc: ^9.0.0
  equatable: ^2.0.5
  hive: ^2.2.3
  freezed: ^3.0.6
  drift: ^2.26.0
  drift_flutter: ^0.2.4
  url_launcher: ^6.3.1
  dio: ^5.2.0
  json_annotation: ^4.9.0
  flutter_svg: ^2.1.0
  path_provider: ^2.0.14
  easy_localization: ^3.0.7+1
  provider: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0
  drift_dev: ^2.26.0
  build_runner: ^2.4.15
  go_router_builder: ^2.9.0
  melos: ^4.0.0
  flutter_dotenv: ^5.2.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/
    - assets/translation/
    - assets/secrets/secrets.env